### ISSUE TITLE
Error when adding snapshot through the edit indicator interface

### ISSUE THREAD

**Issue by allthesignals** [MAPC/regionalindicators#14]
![pasted_image_at_2016_12_30_12_21_pm](https://cloud.githubusercontent.com/assets/5004319/21569450/ded68b00-ce8a-11e6-836f-a9b45175ccdd.png)

**Comment by allthesignals** [comment]
Logs:

2016-12-30T17:25:20.481230+00:00 app[web.1]:   Parameters: {"utf8"=>"✓", "authenticity_token"=>"jYCraOZFuc5xtn/wxStIy22M1qja3/T1cwqYU/m2Dqg=", "snapshot"=>{"date"=>"January 01, 2009 00:00", "rank"=>"", "indicator_id"=>"463", "value"=>"129300"}, "return_to"=>"http://www.regionalindicators.org/admin/snapshot", "_save"=>"", "model_name"=>"snapshot"}
2016-12-30T17:25:20.520128+00:00 app[web.1]: Completed 500 Internal Server Error in 39ms
2016-12-30T17:25:20.522945+00:00 app[web.1]: 
2016-12-30T17:25:20.522947+00:00 app[web.1]: NoMethodError (undefined method `-' for nil:NilClass):
2016-12-30T17:25:20.522948+00:00 app[web.1]:   app/models/indicator.rb:147:in `update_rank_delta'
2016-12-30T17:25:20.522948+00:00 app[web.1]:   app/models/snapshot.rb:43:in `update_indicator'

**Comment by allthesignals** [comment]
This is the indicator in question. When trying to add a snapshot, it throws the above error: http://www.regionalindicators.org/admin/indicator/463/edit

**Comment by allthesignals** [comment]
It seems I can add snapshots through the resource page itself (rather than through the nested form in Indicators).

**Comment by allthesignals** [comment]
I think some of these snapshots aren't logically "rankable" so people aren't filling out that field even though it's technically required.

**Comment by allthesignals** [comment]
Doesn't require rank anymore, still always requires indicator. Users need to create the indicator first before trying to add a snapshot.
